image: archlinux
packages:
  - go
  - pam
  - scdoc
  - curl
sources:
  - https://github.com/foxcpp/maddy
tasks:
  - build: |
      cd maddy
      go build ./...
  - buildsh: |
      cd maddy
      ./build.sh
      ./build.sh --destdir destdir/ install
      find destdir/
  - test: |
      cd maddy
      go test ./... -coverprofile=coverage.out -covermode=atomic -race
  - integration-test: |
      cd maddy/tests
      ./run.sh
  - lint: |
      curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.33.0
      cd maddy/
      $(go env GOPATH)/bin/golangci-lint run || true
  - build-man-pages: |
      cd maddy/docs/man
      for f in *.scd; do scdoc < $f > /dev/null; done
  - upload-coverage: |
      export CODECOV_TOKEN=a4598288-4c29-4da7-87cf-64a36e23d245
      cd maddy/
      bash <(curl https://codecov.io/bash) -f coverage.out -F unit
      cd tests/
      bash <(curl https://codecov.io/bash) -f coverage.out -F integration
